services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_DB=ics'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    labels:
      - "org.springframework.boot.service-connection=postgres"
